Repository Seluj78/PyMatcha, pull requests merged in 2019-01, with the labels that each got.

#22 Added flask-admin
  .travis.yml
  PyMatcha/__init__.py
  PyMatcha/routes/views/home.py
  app.py
  pyproject.toml
  requirements.txt
Labels: enhancement

#27 Added dev requirements
  .travis.yml
  requirements-dev.txt
  requirements.txt
Labels: back-end, enhancement, infra

#28 Add run.sh script
  run.sh
Labels: enhancement, infra

#29 Removed mypy
  .pre-commit-config.yaml
  .travis.yml
  README.md
  requirements-dev.txt
Labels: infra

#25 Added pytest and base tests
  .travis.yml
  PyMatcha/__init__.py
  PyMatcha/routes/api/ping_pong.py
  PyMatcha/tests/__init__.py
  PyMatcha/tests/api/__init__.py
  PyMatcha/tests/api/test_ping_pong_endpoint.py
  PyMatcha/tests/test_config.py
  PyMatcha/tests/test_live_server.py
  PyMatcha/tests/views/__init__.py
  PyMatcha/tests/views/test_view_admin.py
  PyMatcha/tests/views/test_view_home.py
  conftest.py
  requirements.txt
Labels: enhancement, infra
